version: '2'

volumes:
  logs:
    driver: local

services:
  portfolio:
    container_name: portfolio
    #restart: always
    build:
      context: .
      args:
        - SERVER_NAME=www.cgoedefroit.com
        - SERVER_ADMIN=support@magicorp.fr
    environment:
      docker: "true"
