version: '2'

volumes:
    logs:
        driver: local

services:
    portfolio:
        container_name: portfolio
        image: php:7-alpine
        working_dir: /var/www
        command: "/bin/sh -c \"php composer.phar install && php -S 0.0.0.0:8080 -t public\""
        environment:
            docker: "true"
        ports:
            - 8080:8080
        volumes:
            - .:/var/www
            - logs:/var/www/logs
